### ISSUE TITLE
0.0.1: pep517 build fails (missing requirements.txt in sdist tar ball)

### ISSUE THREAD

**Issue by kloczek** [Bartpab/meson-py#3]
As long as there is no got tag for 0.0.1 I've tested sdist pypi tar ball.
```console
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 4, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by kloczek** [comment]
gentle ping .. 🤔

**Comment by sassy-crick** [comment]
I got the same problem. :-(

**Comment by paulocen** [comment]
README.md too. Solution is to copy over the requires.txt in `.egg-info` and put it in the root as requirements.txt and create and empty README.md and install locally with `python3 -m pip install -e <path>`

**Comment by rgommers** [comment]
Hi, I think you're all in the wrong place here. You're trying to use `meson-python` probably, not this `MesonPy` package.
